### ISSUE TITLE
Overseer API Error

### ISSUE THREAD

**Issue by brandonjones24** [Supergamer1337/media-cleaner#3]
Overseer version 1.32.5
media-cleaner-v0.1-linux-x64

```
Error: 
   0: error decoding response body: missing field `pageInfo` at line 1 column 75
   1: missing field `pageInfo` at line 1 column 75

Location:
   src/overseerr/api.rs:14

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Thanks for putting this together, excited to get it working and clean up my library!

**Comment by Supergamer1337** [comment]
What does your `config.yaml` look like?

**Comment by brandonjones24** [comment]
```
items_shown: 5
overseerr:
    url: http://192.168.0.134:5055
    api_key: MTY0NDc1NxxxxxxxxwMTxxxxxxxxxxRkYSk
tautulli:
    url: http://192.168.0.18:8181
    api_key: 6d686fxxxxxxxxxxxxc286d63a
tmdb:
    v3_key: 4f7a5f7f6xxxxxxxxxxxxxxxxxxxx
sonarr:
    url: http://192.168.0.132:8989
    api_key: abe3fexxxxxxxxxxxxxxxxxxx
radarr:
    url: http://192.168.0.132:7878
    api_key: 7139e9b88dd7xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
